---
title: "tabashnikova_daria_161_kr_4"
author: "tabashnikova_daria"
date: "05 06 2018"
output: html_document
---
``` {r message = FALSE, warning = FALSE}
library(tidyverse)
library(maxLik)
library(nyflight13)
```

### ???????????? 1.
```{r}
n_sim <- 10^4
set.seed(68) #k=12
all <- tibble(x = rpois(n_sim, lambda = 10),
              y = rnorm(n_sim, mean = 2, sd = 1),
              z = rbinom(n_sim, size = 24, prob = 1/2),
              w = dunif(n_sim, min=2, max=20))
              
```
              
???????????? ???????????? ????????????????.

```{r}

all2 <- mutate(all, d = exp(y), 
               t = d*x, 
                q=z*w,
            event1 = t>q,
            event2 = z>x,
            event3 = event2/event1)
              
```
?????????????????????? ???????????? 
```{r}
mean(all2$t)
```
?????????????????? ????????????
```{r echo = FALSE}
var(all2$t)
```
?????????????????????? ????????, ?????? ???????????? ???????????????? ????????????
```{r}
mean(all2$event1)

```
???????????????? ??????????????????????
```{r}
mean(all2$event3)

```
### ???????????? 2.
??????????????????????
```{r}
qplot(data = weather, x = humid, xlab = "??????????????????", ylab = "???????????????????? ??????????????" )+
geom_histogram()
```

?????????????????? ??????????????????
```{r}           
plot(data=weather, x=precip, xlab = "??????????????????", ylab = "???????????????????? ??????????????")  
```
?????????????????????????????? ?????????????? ??????????????????????????
```{r}           
  logl <- function(theta, x) {
  
  mu <- theta[1]
  sigma2 <- 370
  n <- length(x)
  
  res <- -n / 2 * log(sigma2) - 1 / 2 / sigma2 * sum((x - mu)^2)
  
  return(res)
}        
```
???????????????????????? ?????????????? ??????????????????????????
```{r}           
 theta_0 <- c(8, 1)
model <- maxLik(logl, start = theta_0, x = x)
summary(model)         
```
  
              
              