---
title: "Контрольная 4"
author: "Марина"
output: html_document
lang: ru_RU
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(maxLik)
```

Упражнение 1

Известно, что $X \sim Exp(\lambda=3)$, $\sim N(7, 25)$, 
$ \sim Binom(n=5, p=1/3)$.

Найдите $P(XY>Z+Y)$, $$

```{r}
n_sim <- 10^4
set.seed(68)
all <- tibble(x=rexp(n_sim, rate = 3), 
              y = rnorm(n_sim, mean = 7, sd = 5),
              z=rbinom(n_sim, size = 5, prob=1/3))
              
```
Оценим требуемые параметры
```{r}
all2 <- mutate(all, d = (x+y)/(y+z), w= x*y,
              event = x*y > z  + y)
```

$P(XY>(X+Y))$ 
```{r}
mean(all2$event)

```
$E\left (\frac{X+Y}{Y+Z})$
```{r}
mean(all2$d)
```
<!-- Комментарий -->

$Var(XY)$
```{r, echo = FALSE, message = FALSE, warning = FALSE} 

var(all2$w)
```
Упражнение 2. 

Величины $X_i$ нормальны $N(\mu, \sigma^2)$.
В качестве $X_i$ возьмите цены бриллиантов из втроенного набора.

```{r}
qplot(data=diamonds, x=log(price))
x <- log(diamonds$price)
```
Определим лог-функцию правдоподобия:
```{r}
logl <- function(theta, x) {
  mu = theta[1]
  sigma2 <- theta[2]
  n <- length(x)
  res <- -n/2*log(sigma2) - 1/2/sigma2 * sum((x-mu)^2)
return(res)
}
```
Максимизируем правдоподобие

```{r}
theta_0 <- c(8, 1)
model <- maxLik(logl, start = theta_0, x=x)
summary(model)
```


