---
title: "yuzvak_egor_161_kr_4"
author: "YuzvakEgor"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library (tidyverse)
library (nycflights13)
library (maxLik)
```

Задача 1

Известно $X \sim pois(\lambda = 10)$, $Y \sim N(2, 1)$, $Z \sim Binom(n=12, p=1/2$, $Q \runif(n, min=2, max =20).

```{r}
n_sim <- 10^4
set.seed(57)
all <- tibble(x = rpois(n_sim, lambda = 10),
              b = rnorm(n_sim, mean = 2, sd = 1),
              z = rbinom(n_sim, size = 12, prob = 1/2),
              c = runif(n_sim, min = 2, max = 20))
```
Вспомогательные переменные: 
```{r message = FALSE, warning = FALSE}
n_sim2 <- mutate(all, w = x * b, q = z *c )
```

Оценка мат. ожидания для w:
```{r}
mean(n_sim2$w)
```
Оценка дисперсии для w:
```{r}
var(n_sim2$w)
```
Оценка мат. ожидания для q:
```{r}
mean(n_sim2$q)
```
Оценка дисперсии для q:
```{r}
var(n_sim2$q)
```

Добавим переменные:
```{r}
all_2 <- mutate(all, event = x * b > z * c)
```

Найдем вероятность, что Василий тратит больше за один день, чем Андрей:
```{r}
mean(all_2$event)
```


```{r}
table1 <- mutate(table, b1 = exp(b),
                 sum1 = b1 * a,
                 sum2 = x * y,
                 event = sum1 > sum2,
                 event1 = (a>x) & (sum1 > sum2))
mean(table1$sum1)
```

Задача 2
1 пункт:
```{r}
hist(weather$humid, breaks = 20, freq = FALSE, col = "lightgreen",
xlab = "Y",
ylab = "Влажность",
main = "Влажность (гистограмма)")
```
2 пункт:
```{r}
ggplot(weather, aes(x=weather$humid, y=weather$precip)) +geom_point() + scale_y_continuous(trans='log') +labs(title="Рассеяния переменных влажность и количество осадков", x="Amount of Humid", y="Amount of Precip")
```







