---
title: "Контрольная 4. Rrrrr-parrrt!"
author: "Винни-Пух"
date: "5 июня 2018"
output: html_document
lang: ru-RU
---

Поехали!

Работа сдаётся только в виде запроса pull-request на репозиторий [github.com/bdemeshev/kr_4_2018_spring_r_part](https://github.com/bdemeshev/kr_4_2018_spring_r_part).

Имя файла должно быть вида `ivanov_ivan_161_kr_4.Rmd`.

Также фамилию и имя нужно указать в шапке документа в поле `author` :)


Если нужно, то установите пакеты `tidyverse`, `maxLik`, `nycfligths13`.

### Симулируем бурную деятельность!

В качестве параметра $k$ в задаче используй число букв в своей фамилии в именительном падеже :)

Каждый день Василий съедает случайное количество булочек, которое распределено по Пуассону с параметром $10$. 
Логарифм затрат в рублях на каждую булочку распределён нормально $N(2, 1)$.  
Андрей каждый день съедает биномиальное количество булочек $Bin(2k, 0.5)$. 
Затраты Андрей на каждую булочку распределены равномерно на отрезке $[2;20]$.

1. Сколько в среднем тратит Василий на булочки за день? 

2. Чему равна дисперсия дневных расходов Василия?

3. Какова вероятность того, что за один день Василий потратит больше денег, чем Андрей?

4. Какова условная вероятность того, что Василий за день съел больше булочек, чем Андрей, если известно, что Василий потратил больше денег?

### Сражаемся с реальностью!

В пакете `nycflights13` встроен набор данных `weather` о погоде в разные дни в разных аэропортах.


1. Постройте гистограмму переменной влажность, `humid`. У графика подпишите оси! 

2. Постройте диаграмму рассеяния переменных влажность и количество осадков, `precip`. У графика подпишите оси! 

3. Посчитайте выборочное среднее и выборочную дисперсию влажности и количества осадков.

4. С помощью максимального правдоподобия оцените параметр $\mu$, предположив, что наблюдения за влажностью имеют нормальное $N\left(\mu, 370\right)$-распределение и независимы.
Постройте 95\%-ый доверительный интервал для $\mu$.

5. С помощью максимального правдоподобия оцените параметр $\sigma^2$, предположив, что наблюдения за влажностью имеют нормальное $N\left(60, \sigma^2\right)$-распределение и независимы. Постройте 95\%-ый доверительный интервал для $\sigma^2$.

Если при численной оптимизации параметр $\sigma^2$ становится отрицательным, можно задать параметры по-другому, например, $\sigma^2 = \exp(\gamma)$.


<!--

5. С помощью максимального правдоподобия оцените параметры $\mu$, $\sigma^2$, предположив, что наблюдения за влажностью имеют нормальное $N(\mu, \sigma^2)$-распределение и независимы, однако усечены снизу нулём, а сверху — числом 100. Другими словами, оцените параметры модели
\[
humid_i = 
\begin{cases}
0, \text{ если } W_i < 0; \\
W_i, \text{ если } W_i \in [0;100]; \\
100, \text{ если } W_i > 100; \\
\end{cases},
\]
где $W_i \sim N(\mu, \sigma^2)$.

-->









